Rate limiting
AltCamp/altcampv1-backend pull request #119
Opened 2023-05-18 13:43 UTC by Peter-TMK

This PR...

## Changes

-

## Fixes
-

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test
- [ ] linter passes
- [ ] format check passes

Fixes #111

2023-05-18 13:55 UTC, tobisupreme commented
before we merge this PR, let us provide tests for this. What do you think?

2023-05-18 14:29 UTC, Peter-TMK commented
Owh! Sure...

On Thu, May 18, 2023, 2:55 PM Tobi Balogun ***@***.***> wrote:

> before we merge this PR, let us provide tests for this. What do you think?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AltCamp/altcampv1-backend/pull/119#issuecomment-1553094375>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMSVEBPKQXFHJOGQQLXHB3DXGYS4VANCNFSM6AAAAAAYGPOHIE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-05-19 03:32 UTC, tobisupreme requested changes

2023-05-19 03:32 UTC, tobisupreme commented on app.js
> +const limiter = rateLimiter({
Moving this code block to a separate module will help, at least regarding reusability.

2023-05-22 10:05 UTC, closed without merging