New email verification
AltCamp/altcampv1-backend pull request #179
Opened 2023-06-23 20:43 UTC by Skywonda

This PR...

## Changes

-

## Fixes
-

## Checklist

-  tested locally
- [ added new dependencies
- [ ] updated the Swagger API docs
- [ ] updated the Postman collection
- [ ] added a test
-  linter passes
- [ ] format check passes

Fixes #

2023-06-23 20:56 UTC, misspee007 approved these changes

2023-06-23 21:22 UTC, tobisupreme requested changes

2023-06-23 21:22 UTC, tobisupreme commented on utils/sendMails.js
> +      console.log(error);
Please remove debuggers

2023-06-23 21:22 UTC, tobisupreme commented on utils/sendMails.js
> +      console.log('Email sent: ' + info.response);
Please remove debuggers

2023-06-23 21:22 UTC, tobisupreme commented on utils/sendMails.js
> +      type: 'OAUTH2',
We should ___refactor___ this so that we do not use hardcoded values on lines `13` and `17`

2023-06-23 21:22 UTC, tobisupreme commented on src/auth/authController.js
> +  res.json({ msg: 'Email verified successfully!' });
For uniformity, let's use the response class, like on line `56`

2023-06-24 19:47 UTC, tobisupreme approved these changes

2023-06-24 20:36 UTC, merged